# Generated by Django 5.2 on 2025-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_fabricacao', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo_combustivel', models.CharField(choices=[('G', 'Gasolina'), ('E', 'Etanol'), ('F', 'Flex'), ('D', 'Diesel'), ('E+', 'Elétrico'), ('H', 'Híbrido')], max_length=2)),
                ('quilometragem', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
