# Generated by Django 5.2 on 2025-04-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='descricao',
            field=models.TextField(blank=True, default='Sem descrição'),
        ),
        migrations.AddField(
            model_name='carro',
            name='img',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
        migrations.AddField(
            model_name='carro',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
