# Generated by Django 5.2 on 2025-04-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_carro_descricao_carro_img_carro_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='url',
        ),
    ]
